services:
  - type: web
    name: app
    env: docker
    docker:
      file: Back/Dockerfile
    buildCommand: ./Back/mvnw clean package -DskipTests
    startCommand: java -jar Back/target/Bybysitting-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        value: jdbc:mysql://bybysitting-db:3306/childcare?createDatabaseIfNotExist=true&serverTimezone=UTC
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 12345
    ports:
      - port: 8080
    dependencies:
      - name: bybysitting-db
    autoDeploy: true

  - type: database
    name: bybysitting-db
    databaseType: mysql
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: 12345
      - key: MYSQL_PASSWORD
        value: 12345
      - key: MYSQL_DATABASE
        value: childcare
    disk:
      name: data_mysql
      mountPath: /var/lib/mysql
    ports:
      - port: 3306
    autoDeploy: true

volumes:
  data_mysql:
    persistent: true
